# Generated by Django 2.2.9 on 2020-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('T', 'to do'), ('D', 'doing'), ('C', 'done')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
