# Generated by Django 2.2.9 on 2020-01-27 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker_app', '0006_upvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upvote',
            new_name='Vote',
        ),
    ]
